(function(){
'use strict';
const $=id=>document.getElementById(id);
const pools=Array.from($('sodaPool').options).map((o,i)=>{const label=o.textContent.trim();return {id:i<14?label.match(/^\d+/)[0]:'—',name:i<14?label.replace(/^\d+\s*[-—]\s*/, ''):label.replace(/^—\s*[-—]?\s*/, '')}});
const poolInputs=['sodaPool','fcPool','cyaPool','dechlorPool','calPool','alkPool'];
const group=i=>i<14?'Aquatica':i<22?'SeaWorld':'Discovery Cove';
const stored=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
let current=stored('field.pool',0), recent=stored('field.recent',[0]),section='home';
if(!Number.isInteger(current)||current<0||current>=pools.length)current=0;
const task=(icon,title,desc,action)=>`<button class="task-button" type="button" data-action="${action}"><span class="task-icon" aria-hidden="true">${icon}</span><span><strong>${title}</strong><small>${desc}</small></span><span class="task-arrow" aria-hidden="true">›</span></button>`;
const shell=document.createElement('div');shell.innerHTML=`<header class="field-header"><div><h1>SeaWorld</h1><small>Field Service</small></div><span class="test-status" id="fieldSyncStatus">Shared logging</span></header><div class="pool-context"><div><small id="fieldProperty"></small><strong id="fieldPool"></strong></div><button class="field-button" id="changePool" type="button">Change</button></div><section id="fieldHome" class="task-page active"><h2>What do you need to do?</h2><div class="task-list">${task('⚗','Calculate Dose','Chlorine • pH • Alkalinity • CYA','calculate')}${task('◴','Check & Calibrate','Readings, calibration & history','calibration')}${task('▤','Feeder Cleaning','Feed down, clean & track','feeders')}${task('⚒','Service Tools','Pumps • Reports • Lab sheets','tools')}</div><div class="recent-title"><h3>Recent pools</h3></div><div id="recentPools" class="recent-pools"></div><p class="field-help">Calibration and feeder updates use the shared service log.</p></section><section id="fieldCalculate" class="task-page"><h2>Calculate Dose</h2><div class="task-list">${task('⚗','Chlorine Feed','Adjust chlorine with the installed feeder','fc')}${task('▣','Manual Chlorination','Granular cal hypo dosing','calhypo')}${task('↗','Raise pH','Soda ash dosing','soda')}${task('⚖','Alkalinity','Sodium bicarbonate dosing','alk')}${task('◉','CYA Dosing','Stabilizer dosing','cya')}${task('↘','Dechlorination','Reduce free chlorine','dechlor')}</div></section><section id="fieldTools" class="task-page"><h2>Service Tools</h2><div class="task-list">${task('⚒','Pump Tools','Pump curves, sizing & field readings','pump')}${task('⚗','Chemical Feed Pump','Stenner sizing & chlorine output','chemfeed')}${task('☎','Incident Report','Record a call and share a PDF','incident')}${task('▤','Lab Sheets','Photos & submission history','labs')}${task('⇄','Utilities','Conversions & dilution','utilities')}</div></section>`;
document.querySelector('.wrap').prepend(shell);
const nav=document.createElement('nav');nav.className='field-bottom';nav.setAttribute('aria-label','Main navigation');nav.innerHTML=[['home','⌂','Home'],['calculate','⚗','Calculate'],['calibration','◴','Calibration'],['feeders','▤','Feeders']].map(([key,icon,label])=>`<button type="button" data-action="${key}"><span aria-hidden="true">${icon}</span>${label}</button>`).join('');document.body.append(nav);
const dialog=document.createElement('dialog');dialog.className='pool-dialog';dialog.innerHTML='<header><h2>Choose pool</h2><button class="field-button" type="button" id="closePool">Close</button></header><label for="poolSearch">Search property, pool name or number</label><input id="poolSearch" type="search" placeholder="501, Kraken, Aquatica…"><div class="pool-results" id="poolResults"></div>';document.body.append(dialog);
function poolLabel(i){const p=pools[i];return (p.id==='—'?'':p.id+' ')+p.name}
function syncFrame(){const f=$('calibrationFrame');if(f?.contentWindow?.setFieldPool)f.contentWindow.setFieldPool(group(current),pools[current].id==='—'?pools[current].name:pools[current].id)}
function choosePool(i){current=i;localStorage.setItem('field.pool',JSON.stringify(i));recent=[i,...recent.filter(v=>v!==i)].slice(0,3);localStorage.setItem('field.recent',JSON.stringify(recent));poolInputs.forEach(id=>{const el=$(id);if(el){el.value=String(i);el.dispatchEvent(new Event('change',{bubbles:true}));el.dispatchEvent(new Event('input',{bubbles:true}))}});$('fieldProperty').textContent=group(i);$('fieldPool').textContent=poolLabel(i);$('recentPools').innerHTML=recent.filter(v=>pools[v]).map(v=>`<button type="button" data-pool="${v}">${poolLabel(v)}<small>${group(v)}</small></button>`).join('');syncFrame()}
function results(){const q=$('poolSearch').value.toLowerCase().trim();$('poolResults').innerHTML=pools.map((p,i)=>({p,i})).filter(({p,i})=>(group(i)+' '+p.id+' '+p.name).toLowerCase().includes(q)).map(({i})=>`<button type="button" data-pool="${i}">${poolLabel(i)}<small>${group(i)}</small></button>`).join('')||'<p>No matching pools.</p>'}
$('changePool').onclick=()=>{results();dialog.showModal();$('poolSearch').focus()};$('closePool').onclick=()=>dialog.close();$('poolSearch').oninput=results;
const oldShow=window.showTab;
window.showTab=function(name){section=name;['Home','Calculate','Tools'].forEach(k=>$('field'+k).classList.toggle('active',name===k.toLowerCase()));oldShow(['home','calculate','tools'].includes(name)?'home':name);nav.querySelectorAll('button').forEach(b=>{const active=b.dataset.action===name||(b.dataset.action==='calculate'&&['soda','fc','cya','calhypo','alk','dechlor'].includes(name));b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});if(name==='calibration'||name==='feeders')syncFrame()};
document.addEventListener('click',e=>{const b=e.target.closest('[data-action],[data-pool]');if(!b)return;if(b.dataset.pool!==undefined){choosePool(Number(b.dataset.pool));if(dialog.open)dialog.close()}else if(b.dataset.action==='labs')location.href='lab-sheets.html';else showTab(b.dataset.action)});
poolInputs.forEach(id=>$(id)?.addEventListener('change',()=>{const i=Number($(id).value);if(i!==current)choosePool(i)}));
$('calibrationFrame').addEventListener('load',syncFrame);
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==$('calibrationFrame').contentWindow)return;if(e.data?.type==='field-pool'){const i=pools.findIndex((p,n)=>group(n)===e.data.property&&(p.id==='—'?p.name:p.id)===e.data.id);if(i>=0&&i!==current)choosePool(i)}if(e.data?.type==='field-sync'){$('fieldSyncStatus').textContent=e.data.status;}if(e.data?.type==='field-view'){section=e.data.view==='feeders'?'feeders':'calibration';nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.action===section))}});
document.querySelectorAll('.reference-section,.formula-card').forEach(el=>{const d=document.createElement('details');d.className='field-reference';const sum=document.createElement('summary');sum.textContent=el.classList.contains('formula-card')?'Formula & calculation details':'Quick reference';el.before(d);d.append(sum,el)});
choosePool(current);const route=location.hash.slice(1);showTab(['home','calculate','tools','calibration','feeders'].includes(route)?route:'home');
})();
